version: '3'
services:

  mysql:
    image: mysql:5.7
    restart: always
    ports:
     - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    volumes:
     - ./mysql:/var/lib/mysql
    environment:
     - TZ=Asia/Shanghai
     - MYSQL_ROOT_PASSWORD=gddlkj123456
    networks:
     - default

  redis:
    restart: always
    image: redis:3.2
    container_name: redis
    environment:
     - TZ=Asia/Shanghai
    volumes:
     - ./redis:/data
    ports:
     - "6379:6379"
    command: redis-server --appendonly yes --requirepass "gddlkj123456"
    networks:
      - default


  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./moongo/mongdb1:/data/db
      - ./moongo/setup:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: gddlkj123456
    networks:
      - default

  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - default

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    ports:
      - "9000:9000"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - default

networks:
  default:
    external:
      name: blank-network



