#数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.3.5:3306/jmjkzx?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: jkzxuser
    password: jk123456
  redis:
    #数据库索引
    database: 4
    host: 192.168.0.213
    port: 26379
    password: ENC(HZnYD9JFv+CUOwqSb6+mIPZzPsHELasB)
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000


