#数据源
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/example?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: ENC(HZnYD9JFv+CUOwqSb6+mIPZzPsHELasB)
  redis:
    #数据库索引
    database: 0
    host: redis
    port: 6379
    password: ENC(HZnYD9JFv+CUOwqSb6+mIPZzPsHELasB)
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
